GET http://localhost:5000/api/authors?page=4&result=5 HTTP/1.1

###

GET http://localhost:5000/api/authors/10 HTTP/1.1

###

POST http://localhost:5000/api/authors HTTP/1.1
Content-Type: application/json

{
  "full_name": "New Author",
  "email": "n-a@gmail.com",
  "nationality_id": 12
}

###

PUT http://localhost:5000/api/authors HTTP/1.1
Content-Type: application/json

{
  "id": 18,
  "full_name": "Philip Jose Farmer",
  "email": "n-a@gmail.com",
  "nationality_id": 1
}

###
PATCH http://localhost:5000/api/authors/18 HTTP/1.1
Content-Type: application/json

{
  "email": "ph-j-f@gmail.com"
}

###

DELETE  http://localhost:5000/api/authors/19 HTTP/1.1
Content-Type: application/json

